import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import AuthProvider from "@/context/authprovider";
import { SocketProvider } from "../context/socket";
import Footer from "@/components/Footer";
import NavBar from "@/components/navbar/navbarServer";
import { NotificationProvider } from "@/components/notifications/NotificationProvider";

// const session = await auth()
// const user = session?.user

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Career Hub",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Make sure this file exists in the /public folder
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <AuthProvider>
          <SocketProvider>
            <NotificationProvider>
            <NavBar  />
            
            {/* 👇 Add a wrapper with top padding */}
            <main className="pt-[72px]"> {/* Adjust if your navbar height is different */}
              {children}
            </main>

            <Footer />
            </NotificationProvider>
          </SocketProvider>

          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
